version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Only watch for critical dependencies
    allow:
      - dependency-name: "matterbridge"
    open-pull-requests-limit: 2
    reviewers:
      - "andrasg"
    assignees:
      - "andrasg"
    commit-message:
      prefix: "chore"
      include: "scope"
