const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const target = path.join(__dirname, "..", "src", "gitInfo.ts");

/**
 * Runs a git command and returns its trimmed output, or 'unknown' when git is unavailable
 * (for example when the package is installed from a tarball without a .git directory).
 *
 * @param {string} args The git arguments to run.
 * @returns {string} The command output or 'unknown'.
 */
function gitInfo(args) {
  try {
    return execSync(`git ${args}`, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "unknown";
  }
}

const branch = gitInfo("rev-parse --abbrev-ref HEAD");
const commit = gitInfo("rev-parse HEAD");

const content = `// Auto-generated by genGitInfo.cjs
export const GIT_BRANCH = '${branch}';
export const GIT_COMMIT = '${commit}';
`;

if (fs.existsSync(target) && fs.readFileSync(target, "utf8") === content) {
  console.log("src/gitInfo.ts is up to date.");
} else {
  fs.writeFileSync(target, content);
  console.log("src/gitInfo.ts generated.");
}
