name: Build and lint

on:
    push:
        branches-ignore: ['main']
        tags-ignore:
            - 'v*'
    pull_request:
    repository_dispatch:
        types: [matterbridge-updated, critical-dependency-updated]
    workflow_dispatch:
        inputs:
            reason:
                description: 'Reason for manual trigger'
                required: false
                default: 'Manual upstream check'
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 23.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check if relevant dependencies changed
        id: check-deps
        if: github.event_name == 'repository_dispatch'
        run: |
          # Define critical dependencies that should trigger builds
          CRITICAL_DEPS=("matterbridge")
          
          # Check if the dispatch includes dependency info
          if [[ "${{ github.event.client_payload.dependency }}" != "" ]]; then
            CHANGED_DEP="${{ github.event.client_payload.dependency }}"
            echo "Dependency changed: $CHANGED_DEP"
            
            # Check if it's in our critical list
            for dep in "${CRITICAL_DEPS[@]}"; do
              if [[ "$CHANGED_DEP" == "$dep"* ]]; then
                echo "Critical dependency changed: $dep"
                echo "SHOULD_BUILD=true" >> $GITHUB_ENV
                exit 0
              fi
            done
            
            echo "Non-critical dependency changed, skipping build"
            echo "SHOULD_BUILD=false" >> $GITHUB_ENV
            exit 1
          else
            echo "No dependency info provided, proceeding with build"
            echo "SHOULD_BUILD=true" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean cache
        run: npm cache clean --force
    
      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v
            
      - name: Install matterbridge
        run: npm install -g matterbridge --omit=dev

      - name: Install dependencies
        run: npm ci
  
      - name: Link matterbridge
        run: npm link matterbridge

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
