name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean cache
        run: npm cache clean --force
  
      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v
            
      - name: Extract version from release
        id: get_version
        run: |
          # Extract version from tag name (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update package.json version
        run: |
          # Update the version in package.json
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version --allow-same-version
          echo "Updated package.json to version ${{ steps.get_version.outputs.version }}"

      - name: Install matterbridge
        run: npm install -g matterbridge --omit=dev

      - name: Install dependencies
        run: npm ci
    
      - name: Link matterbridge
        run: npm link matterbridge

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
